name: Deploy code to aws lambda

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set environment variables
        run: |
          touch .env
          echo "USER_EMAIL=${{secrets.API_KEY}}" >> .env
          echo "USER_PASSWORD=${{secrets.API_KEY}}" >> .env
      - name: Deploy code to Lambda
        uses: mariamrf/py-lambda-action@v1.0.0
        with:
          lambda_layer_arn: 'arn:aws:lambda:ap-south-1:726050079474:layer:my-layer'
          lambda_function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.REGION }}
