name: Covid vaccine notification

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Set up python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install pipenv
        run: pip install pipenv
      - name: Run pipenv sync
        run: pipenv sync
      - name: Activate pipenv shell
        run: pipenv shell
      - name: Run python code
        run: python app/datacollector.py